//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.09 at 04:04:19 PM MST 
//


package dev.gbuchenberger.aleator.domain.nlp;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}coreference"/>
 *         &lt;element ref="{}mention" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coreference",
    "mention"
})
@XmlRootElement(name = "coreference")
@Entity(name = "Coreference")
@Table(name = "COREFERENCE")
@Inheritance(strategy = InheritanceType.JOINED)
public class Coreference {

    protected Coreference coreference;
    protected List<Mention> mention;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the coreference property.
     * 
     * @return
     *     possible object is
     *     {@link Coreference }
     *     
     */
    @ManyToOne(targetEntity = Coreference.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "COREFERENCE_COREFERENCE_HJID")
    public Coreference getCoreference() {
        return coreference;
    }

    /**
     * Sets the value of the coreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coreference }
     *     
     */
    public void setCoreference(Coreference value) {
        this.coreference = value;
    }

    /**
     * Gets the value of the mention property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mention property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMention().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mention }
     * 
     * 
     */
    @OneToMany(targetEntity = Mention.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MENTION_COREFERENCE_HJID")
    public List<Mention> getMention() {
        if (mention == null) {
            mention = new ArrayList<Mention>();
        }
        return this.mention;
    }

    /**
     * 
     * 
     */
    public void setMention(List<Mention> mention) {
        this.mention = mention;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
